//Quotes array
const quotes = [
    ["The greatest glory in living lies not in never falling, but in rising every time we fall","Nelson Mandela"],
    ["The way to get started is to quit talking and begin doing","Walt Disney"],
    ["If life were predictable it would cease to be life, and be without flavor","Eleanor Roosevelt"],
    ["If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough","Oprah Winfrey"],
    ["If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success","James Cameron"],
    ["Life is what happens when you're busy making other plans","John Lennon"],
    ["Spread love everywhere you go. Let no one ever come to you without leaving happier","Mother Teresa"],
    ["When you reach the end of your rope, tie a knot in it and hang on","Franklin D. Roosevelt"],
    ["Always remember that you are absolutely unique. Just like everyone else","Margaret Mead"],
    ["Don't judge each day by the harvest you reap but by the seeds that you plant","Robert Louis Stevenson"],
    ["The future belongs to those who believe in the beauty of their dreams","Eleanor Roosevelt"],
    ["Tell me and I forget. Teach me and I remember. Involve me and I learn","Benjamin Franklin"],
    ["Do not go where the path may lead, go instead where there is no path and leave a trail","Ralph Waldo Emerson"],
    ["You will face many defeats in life, but never let yourself be defeated","Maya Angelou"],
    ["Never let the fear of striking out keep you from playing the game","Babe Ruth"],
    ["Life is either a daring adventure or nothing at all","Helen Keller"],
    ["Many of life's failures are people who did not realize how close they were to success when they gave up","Thomas A. Edison"],
    ["You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose","Dr. Seuss"],
    ["Life is never fair, and perhaps it is a good thing for most of us that it is not","Oscar Wilde"],
    ["The only impossible journey is the one you never begin","ony Robbins"],
    ["Only a life lived for others is a life worthwhile","Albert Einstein"],
    ["The greatest glory in living lies not in never falling, but in rising every time we fall","Nelson Mandela"],
    ["Life is trying things to see if they work","Ray Bradbury"],
    ["Many of life's failures are people who did not realize how close they were to success when they gave up","Thomas A. Edison"],
    ["Success is not final; failure is not fatal: It is the courage to continue that counts","Winston S. Churchill"],
    ["Success usually comes to those who are too busy to be looking for it","Henry David Thoreau"],
    ["I find that the harder I work, the more luck I seem to have","Thomas Jefferson"],
    ["Don't be distracted by criticism. Remember — the only taste of success some people get is to take a bite out of you","Zig Ziglar"],
    ["Success usually comes to those who are too busy to be looking for it","Henry David Thoreau"],
    ["There are no secrets to success. It is the result of preparation, hard work, and learning from failure","Colin Powell"],
    ["It is better to fail in originality than to succeed in imitation","Herman Melville"],
    ["The road to success and the road to failure are almost exactly the same","Colin R. Davis"],
    ["I failed my way to success","Thomas Edison"],

];

export{quotes}
